spring:
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: demo-app
            client-secret: WDrzRs8Sm9EPSAypodf1Z9K2qficKa6I
            client-name: demo-sample-app
            client-authentication-method: basic
            authorization-grant-type: authorization_code
            scope:
              - openid
              - email
              - profile
        provider:
          keycloak:
            issuer-uri: https://keycloak-iam-clients-dev.apps.ocpbarr.correo.local/auth/realms/customers
            user-name-attribute: name